# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Rifky Docs
site_url: https://rifkyhernanda.github.io/rifky-docs
theme:
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - navigation.top
    - navigation.footer
  logo: assets\comet.png
  favicon: assets\comet.png
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css
extra:
  homepage: https://rifkyhernanda.github.io/rifky-docs/
  consent:
    title: Cookie consent (just to be safe)
    description: >- 
      This sites use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  social:
    - icon: fontawesome/brands/mastodon 
      link: https://fosstodon.org/@squidfunk